### ISSUE TITLE
Uncaught TypeError: Invalid FFI pointer type, expected null, integer or BigInt

### ISSUE THREAD

**Issue by alexgleason** [kriszyp/lmdbx-store#15]
This one I'm not sure how to fix on my own.

```
> let db = open({ path: 'db', compression: true })
Uncaught TypeError: Invalid FFI pointer type, expected null, integer or BigInt
    at eval (eval at DynamicLibrary (internal:ext/ffi/00_ffi.js:455:34), <anonymous>:4:13)
    at allocateFixedBuffer (file:///home/alex/Projects/lmdbx-js/open.js:389:67)
    at open (file:///home/alex/Projects/lmdbx-js/open.js:21:3)
    at <anonymous>:2:10
> 
```

> There was a breaking change in Deno FFI API that split pointer type into two: pointer & buffer.

**Comment by alexgleason** [comment]
Wait, should I just be using lmdb-js? I don't have a specific reason to use lmdbx, lol. This came up first in search.

EDIT: lmdb-js is working perfectly with `npm:lmdb`. This library has errors even with the npm specifier.

**Comment by kriszyp** [comment]
Yes, you should be using lmdb-js (`npm:lmdb`), unless you have a specific need for lmdbx. lmdb-js is much more maintained, and I haven't had a chance to apply a lot of these recent updates for Deno to lmdbx.
